controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /index
        permanent: true